sonar.projectKey=javiersanchezdolera777-blip_suplementos-comparator
sonar.organization=javiersanchezdolera777-blip

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=suplementos-comparator
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=frontend/src,backend

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/venv/**,**/.venv/**,**/__pycache__/**,**/.next/**,**/alembic/**

# Tests exclusions
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx,**/tests/**,**/test_*.py
