"""Migración inicial (Baseline)

Revision ID: 76f91c8ef1eb
Revises: 
Create Date: 2026-08-15 16:15:57.375673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f91c8ef1eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_productos_sin_gluten'), 'productos', ['sin_gluten'], unique=False)
    op.create_index(op.f('ix_productos_sin_lactosa'), 'productos', ['sin_lactosa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_sin_lactosa'), table_name='productos')
    op.drop_index(op.f('ix_productos_sin_gluten'), table_name='productos')
    # ### end Alembic commands ###
