"""migracion_multitienda

Revision ID: 8461f0f87f26
Revises:
Create Date: 2026-08-29 02:56:53.137559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8461f0f87f26"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. CREAMOS LA TABLA MANUALMENTE (Alembic no la detectó)
    op.create_table(
        "ofertas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("tienda", sa.String(), nullable=False),
        sa.Column("precio", sa.Float(), nullable=False),
        sa.Column("precio_anterior", sa.Float(), nullable=True),
        sa.Column("precio_por_kg", sa.Float(), nullable=True),
        sa.Column("afiliado_url", sa.String(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True, default=True),
        sa.Column("publicado_telegram", sa.Boolean(), nullable=True, default=False),
        sa.Column("fecha_publicacion_telegram", sa.DateTime(), nullable=True),
        sa.Column("ultima_actualizacion", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["producto_id"], ["productos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ofertas_id"), "ofertas", ["id"], unique=False)
    op.create_index(op.f("ix_ofertas_tienda"), "ofertas", ["tienda"], unique=False)

    # 2. INYECCIÓN SQL: SALVAMOS LOS DATOS (Zero-Data-Loss)
    op.execute(
        """
        INSERT INTO ofertas (producto_id, tienda, precio, precio_anterior, precio_por_kg, afiliado_url, activo, publicado_telegram, fecha_publicacion_telegram, ultima_actualizacion)
        SELECT id, COALESCE(tienda, 'Desconocida'), precio, precio_anterior, precio_por_kg, COALESCE(afiliado_url, ''), true, publicado_telegram, fecha_publicacion_telegram, NOW()
        FROM productos;
        """
    )

    # 3. COMANDOS DE ALEMBIC (Actualizamos el índice y borramos las columnas viejas)
    op.drop_index(op.f("ix_productos_slug"), table_name="productos")
    op.create_index(op.f("ix_productos_slug"), "productos", ["slug"], unique=False)
    op.drop_column("productos", "fecha_publicacion_telegram")
    op.drop_column("productos", "precio")
    op.drop_column("productos", "precio_por_kg")
    op.drop_column("productos", "precio_anterior")
    op.drop_column("productos", "publicado_telegram")
    op.drop_column("productos", "afiliado_url")
    op.drop_column("productos", "tienda")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "productos",
        sa.Column("tienda", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "productos",
        sa.Column("afiliado_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "productos",
        sa.Column(
            "publicado_telegram", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "productos",
        sa.Column(
            "precio_anterior",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "productos",
        sa.Column(
            "precio_por_kg",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "productos",
        sa.Column(
            "precio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "productos",
        sa.Column(
            "fecha_publicacion_telegram",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_productos_slug"), table_name="productos")
    op.create_index(op.f("ix_productos_slug"), "productos", ["slug"], unique=False)
    # ### end Alembic commands ###
