"""add_control_spam_retargeting

Revision ID: 84b3d54ecfc6
Revises: 88afb8efc0e7
Create Date: 2026-08-17 03:36:27.710708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b3d54ecfc6'
down_revision: Union[str, Sequence[str], None] = '88afb8efc0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('fecha_ultimo_retargeting', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha_ultimo_retargeting')
    # ### end Alembic commands ###
