"""add_historial_vistas

Revision ID: 88afb8efc0e7
Revises: bce3f50d0c9e
Create Date: 2026-08-17 03:23:56.348872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88afb8efc0e7'
down_revision: Union[str, Sequence[str], None] = 'bce3f50d0c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
