"""Crear tabla suscripciones_newsletter

Revision ID: bce3f50d0c9e
Revises: 76f91c8ef1eb
Create Date: 2026-08-17 02:01:43.924578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce3f50d0c9e'
down_revision: Union[str, Sequence[str], None] = '76f91c8ef1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_marcas_nombre_trgm'), table_name='marcas', postgresql_ops={'nombre': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_productos_nombre_trgm'), table_name='productos', postgresql_ops={'nombre': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_productos_nombre_trgm'), 'productos', ['nombre'], unique=False, postgresql_ops={'nombre': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_marcas_nombre_trgm'), 'marcas', ['nombre'], unique=False, postgresql_ops={'nombre': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
